import { useCallback, useEffect, useRef, useState } from "react";
import type { CommandRecord, CommandType } from "../../../packages/contracts/src/index";
import { bootstrapAuth, cancelCommand, createCommand, enableTotp, getAudit, getCommandEvents, getCommands, getDashboard, login, logout, retryCommand, setupTotp } from "./api";

type Tab = "dashboard" | "scrapers" | "news" | "automation" | "videos" | "channels" | "commands" | "audit" | "settings";
const nav: Array<[Tab, string, string]> = [["dashboard", "Resumen", "⌂"], ["scrapers", "Scrapers", "⌁"], ["news", "Noticias", "▤"], ["automation", "Automatización", "⚙"], ["videos", "Videos", "▶"], ["channels", "Canales", "◉"], ["commands", "Comandos", "⇄"], ["audit", "Auditoría", "☷"], ["settings", "Seguridad", "◆"]];
const platforms = ["web", "instagram", "facebook", "whatsapp", "x"];

export function App() {
  const [user, setUser] = useState<any>(null); const [checking, setChecking] = useState(true); const [tab, setTab] = useState<Tab>("dashboard");
  const [dashboard, setDashboard] = useState<any>(null); const [commands, setCommands] = useState<CommandRecord[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const refresh = useCallback(async () => { if (!user) return; try { const [d, c] = await Promise.all([getDashboard(), getCommands()]); setDashboard(d); setCommands(c.items); setError(""); } catch (e) { setError(message(e)); } }, [user]);
  useEffect(() => { bootstrapAuth().then(setUser).catch(() => undefined).finally(() => setChecking(false)); }, []);
  useEffect(() => { if (!user) return; void refresh(); const timer = setInterval(refresh, 5000); return () => clearInterval(timer); }, [user, refresh]);
  const run = async (type: CommandType, payload: Record<string, unknown>, success = "Comando encolado") => { try { await createCommand(type, payload); setNotice(success); setError(""); await refresh(); } catch (e) { setError(message(e)); } };
  if (checking) return <div className="center"><div className="loader" /></div>;
  if (!user) return <Login onLogin={setUser} />;
  const snapshots = Object.fromEntries((dashboard?.snapshots ?? []).map((s: any) => [s.key, s]));
  return <div className="shell">
    <aside><div className="brand"><div className="brand-mark">HS</div><div><strong>HolaSalta</strong><span>Operations</span></div></div><nav>{nav.map(([id, label, icon]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><i>{icon}</i>{label}</button>)}</nav><div className="sidebar-foot"><StatusDot online={dashboard?.agent?.online} /> <span>{dashboard?.agent?.online ? "PC conectada" : "PC sin conexión"}</span></div></aside>
    <main><header><div><h1>{nav.find((item) => item[0] === tab)?.[1]}</h1><p>Control remoto seguro · ejecución local</p></div><div className="user"><span>{user.email}</span><button className="ghost" onClick={() => logout().then(() => setUser(null))}>Salir</button></div></header>
      {error && <div className="alert error">{error}<button onClick={() => setError("")}>×</button></div>}{notice && <div className="alert success">{notice}<button onClick={() => setNotice("")}>×</button></div>}
      {tab === "dashboard" && <Dashboard data={dashboard} commands={commands} snapshots={snapshots} run={run} />}
      {tab === "scrapers" && <Scrapers run={run} commands={commands} />}
      {tab === "news" && <News snapshot={snapshots["news.current"]} groups={snapshots["whatsapp.groups"]} run={run} />}
      {tab === "automation" && <Automation snapshots={snapshots} run={run} />}
      {tab === "videos" && <Videos snapshot={snapshots["xvideo.jobs"]} commands={commands} run={run} />}
      {tab === "channels" && <Channels snapshots={snapshots} run={run} />}
      {tab === "commands" && <Commands items={commands} refresh={refresh} />}
      {tab === "audit" && <Audit />}
      {tab === "settings" && <Settings user={user} setUser={setUser} />}
    </main>
  </div>;
}

function Login({ onLogin }: { onLogin(user: any): void }) {
  const [email, setEmail] = useState("holasalta@acceso.com"); const [password, setPassword] = useState(""); const [totp, setTotp] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); try { onLogin(await login(email, password, totp)); } catch (err: any) { setError(err.code === "TOTP_REQUIRED" ? "La cuenta requiere el código de autenticación." : message(err)); } finally { setBusy(false); } };
  return <div className="login-page"><div className="login-card"><div className="brand login-brand"><div className="brand-mark">HS</div><div><strong>HolaSalta Ops</strong><span>Acceso autorizado</span></div></div><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="username" /></label><label>Contraseña<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" autoFocus /></label><label>Código 2FA <small>(si está activado)</small><input inputMode="numeric" maxLength={6} value={totp} onChange={(e) => setTotp(e.target.value.replace(/\D/g, ""))} /></label>{error && <div className="inline-error">{error}</div>}<button className="primary wide" disabled={busy}>{busy ? "Ingresando…" : "Ingresar"}</button></form></div></div>;
}

function Dashboard({ data, commands, snapshots, run }: any) {
  const status = snapshots["automation.status"]?.payload; return <><section className="stats"><Stat label="Agente local" value={data?.agent?.online ? "Conectado" : "Desconectado"} tone={data?.agent?.online ? "good" : "bad"} /><Stat label="Comandos activos" value={data?.counts?.active ?? 0} /><Stat label="Requieren atención" value={data?.counts?.attention ?? 0} tone={data?.counts?.attention ? "warn" : "good"} /><Stat label="Runtime" value={status?.status ?? "Sin datos"} /></section><section className="grid two"><Card title="Acciones rápidas"><div className="actions"><button onClick={() => run("snapshot.refresh", {})}>Actualizar estado</button><button onClick={() => run("scraper.all.titles", { maxArticlesPerSource: 10 })}>Buscar noticias</button><button onClick={() => run("automation.restart", {})}>Reiniciar runtime</button></div></Card><Card title="Estado local"><JsonPreview value={status ?? { message: "Esperando agente" }} /></Card></section><Card title="Actividad reciente"><CommandTable items={commands.slice(0, 10)} /></Card></>;
}

function Scrapers({ run, commands }: any) {
  const [source, setSource] = useState("tn"); const [max, setMax] = useState(20); const [urls, setUrls] = useState("");
  const last = commands.find((c: CommandRecord) => c.type.startsWith("scraper.") && c.result);
  return <section className="grid two"><Card title="Buscar titulares"><Field label="Fuente"><select value={source} onChange={(e) => setSource(e.target.value)}>{["minutouno","tn","na","ambito","aries","justicia","fiscales","nuevodiario","elonce","eloncesalta","eltribuno","infobae","quepasasalta"].map((s) => <option key={s}>{s}</option>)}</select></Field><Field label="Máximo"><input type="number" min={1} max={100} value={max} onChange={(e) => setMax(Number(e.target.value))} /></Field><div className="actions"><button className="primary" onClick={() => run("scraper.titles", { source, maxArticles: max })}>Buscar fuente</button><button onClick={() => run("scraper.all.titles", { maxArticlesPerSource: Math.min(max, 50) })}>Buscar en todas</button></div></Card><Card title="Preparar artículos"><Field label="URLs (una por línea)"><textarea rows={8} value={urls} onChange={(e) => setUrls(e.target.value)} /></Field><button className="primary" onClick={() => run("scraper.details", { source, urls: lines(urls) })}>Procesar artículos</button></Card><Card title="Último resultado" className="span-2"><JsonPreview value={last?.result ?? { message: "Todavía no hay resultados" }} /></Card></section>;
}

function News({ snapshot, groups, run }: any) {
  const [draft, setDraft] = useState<any[]>([]); const [selected, setSelected] = useState<number[]>([]); const [chosen, setChosen] = useState<string[]>(["web"]); const initialized = useRef("");
  useEffect(() => { const hash = snapshot?.contentHash ?? ""; if (hash && initialized.current !== hash) { setDraft(Array.isArray(snapshot?.payload) ? snapshot.payload : []); initialized.current = hash; setSelected([]); } }, [snapshot?.contentHash, snapshot?.payload]);
  const togglePlatform = (p: string) => setChosen((current) => current.includes(p) ? current.filter((x) => x !== p) : [...current, p]);
  return <><Card title="Publicación"><div className="toolbar"><div className="checks">{platforms.map((p) => <label key={p}><input type="checkbox" checked={chosen.includes(p)} onChange={() => togglePlatform(p)} />{p}</label>)}</div><div className="actions"><button onClick={() => run("news.load_wordpress", { perPage: 30 })}>Cargar WordPress</button><button onClick={() => run("news.save", { items: draft })}>Guardar cambios</button><button className="danger" disabled={!selected.length || !chosen.length} onClick={() => run("news.publish", { selectedIndices: selected, platforms: chosen, whatsappGroups: groups?.payload?.groups ?? [], whatsappGroupSet: null, instagramEmojis: true, wixPin: false, wixCategories: false })}>Publicar {selected.length}</button></div></div></Card><div className="news-list">{draft.map((item, index) => <article key={`${item.url ?? "item"}-${index}`} className={selected.includes(index) ? "selected" : ""}><input className="select-news" type="checkbox" checked={selected.includes(index)} onChange={() => setSelected((c) => c.includes(index) ? c.filter((x) => x !== index) : [...c, index])} />{item.imagen && <img src={item.imagen} alt="" />}<div><input className="title-edit" value={item.titulo ?? ""} onChange={(e) => setDraft((current) => current.map((x, i) => i === index ? { ...x, titulo: e.target.value } : x))} /><textarea value={item.extracto ?? ""} onChange={(e) => setDraft((current) => current.map((x, i) => i === index ? { ...x, extracto: e.target.value } : x))} /><small>{item.source ?? "sin fuente"} · {item.url ?? item.web_url ?? ""}</small></div></article>)}{!draft.length && <Empty text="La PC todavía no sincronizó noticias." />}</div></>;
}

function Automation({ snapshots, run }: any) {
  const status = snapshots["automation.status"]?.payload; const jobs = snapshots["automation.jobs"]?.payload?.items ?? []; const pending = snapshots["instagram.pending"]?.payload?.pending ?? [];
  return <><section className="grid two"><Card title="Runtime"><div className="actions"><button onClick={() => run("automation.start", {})}>Iniciar</button><button onClick={() => run("automation.restart", {})}>Reiniciar</button><button className="danger" onClick={() => run("automation.stop", {})}>Detener</button></div><JsonPreview value={status ?? { message: "Sin estado" }} /></Card><Card title="Pendientes Instagram">{pending.map((p: any) => <div className="row" key={p.id}><div><strong>{p.reason}</strong><small>{p.last_error}</small></div><div className="actions"><button onClick={() => run("instagram.pending.retry", { pendingId: p.id })}>Reintentar</button><button className="danger" onClick={() => run("instagram.pending.delete", { pendingId: p.id })}>Eliminar</button></div></div>)}{!pending.length && <Empty text="No hay pendientes." />}</Card></section><Card title="Jobs locales"><table><thead><tr><th>Tipo</th><th>Estado</th><th>Progreso</th><th>Actualizado</th></tr></thead><tbody>{jobs.map((j: any) => <tr key={j.job_id}><td>{j.type}</td><td><Badge status={j.status} /></td><td>{j.progress_percent ?? 0}%</td><td>{shortDate(j.updated_at)}</td></tr>)}</tbody></table></Card></>;
}

function Videos({ snapshot, commands, run }: any) {
  const [url, setUrl] = useState(""); const [title, setTitle] = useState(""); const [caption, setCaption] = useState(""); const [batch, setBatch] = useState(""); const [selectedPlatforms, setSelectedPlatforms] = useState(["facebook", "instagram", "x"]); const jobs = snapshot?.payload?.items ?? [];
  const toggle = (p: string) => setSelectedPlatforms((c) => c.includes(p) ? c.filter((x) => x !== p) : [...c, p]); const exports = commands.filter((c: CommandRecord) => c.type === "xvideo.export_r2" && c.status === "completed");
  return <><section className="grid two"><Card title="Nuevo video desde URL"><Field label="URL de X/YouTube/R2"><input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://…" /></Field><Field label="Título"><input value={title} onChange={(e) => setTitle(e.target.value)} /></Field><Field label="Caption"><textarea rows={5} value={caption} onChange={(e) => setCaption(e.target.value)} /></Field><button className="primary" onClick={() => run("xvideo.create_url", { sourceUrl: url, title, caption, quality: "normal", textMode: "auto" })}>Procesar video</button></Card><Card title="Lote de videos"><Field label="URLs (una por línea)"><textarea rows={10} value={batch} onChange={(e) => setBatch(e.target.value)} /></Field><button className="primary" onClick={() => run("xvideo.batch.create", { sourceUrls: lines(batch), quality: "normal", textMode: "auto", action: "process", platforms: [], whatsappGroups: [], whatsappGroupSet: null })}>Procesar lote</button></Card></section><Card title="Plataformas"><div className="checks">{["facebook","instagram","x","whatsapp"].map((p) => <label key={p}><input type="checkbox" checked={selectedPlatforms.includes(p)} onChange={() => toggle(p)} />{p}</label>)}</div></Card><Card title="Videos locales"><div className="cards">{jobs.map((job: any) => <div className="video-card" key={job.job_id}>{job.job_id && <img src={`/local-placeholder.svg`} alt="" onError={(e) => { e.currentTarget.style.display = "none"; }} />}<strong>{job.title || job.job_id}</strong><Badge status={job.status} /><small>{job.caption?.slice(0, 120)}</small><div className="actions"><button disabled={job.status !== "ready" || !selectedPlatforms.length} onClick={() => run("xvideo.publish", { jobId: job.job_id, platforms: selectedPlatforms, whatsappGroups: [], whatsappGroupSet: null })}>Publicar</button><button disabled={job.status !== "ready"} onClick={() => run("xvideo.export_r2", { jobId: job.job_id, filename: `${job.job_id}.mp4` })}>Subir a R2</button></div></div>)}{!jobs.length && <Empty text="No hay videos sincronizados." />}</div></Card>{exports.length > 0 && <Card title="Descargas R2">{exports.map((c: any) => <div className="row" key={c.id}><span>{c.localJobId}</span><a className="button" href={c.result?.downloadUrl} target="_blank" rel="noreferrer">Descargar</a></div>)}</Card>}</>;
}

function Channels({ snapshots, run }: any) {
  const [wixIds, setWixIds] = useState(""); const wp = snapshots["wordpress.posts"]?.payload ?? []; const groups = snapshots["whatsapp.groups"]?.payload;
  return <section className="grid two"><Card title="WhatsApp"><p>{groups?.count ?? 0} grupos sincronizados.</p><button onClick={() => run("whatsapp.groups.extract", {})}>Extraer grupos</button></Card><Card title="Wix"><Field label="IDs de posts"><textarea rows={5} value={wixIds} onChange={(e) => setWixIds(e.target.value)} /></Field><div className="actions"><button onClick={() => run("wix.pin", { postIds: lines(wixIds) })}>Fijar</button><button onClick={() => run("wix.assign_categories", { postIds: lines(wixIds) })}>Asignar categorías</button></div></Card><Card title="WordPress" className="span-2">{Array.isArray(wp) && wp.slice(0, 30).map((post: any) => <div className="row" key={post.id ?? post.url_wordpress}><div><strong>{post.titulo}</strong><small>{post.url_wordpress}</small></div><button onClick={() => run("wordpress.share", { post, platforms: ["facebook", "x"], whatsappGroups: [], whatsappGroupSet: null, instagramEmojis: true })}>Compartir</button></div>)}</Card></section>;
}

function Commands({ items, refresh }: { items: CommandRecord[]; refresh(): Promise<void> }) {
  const [selected, setSelected] = useState<any>(null); const [events, setEvents] = useState<any[]>([]); const open = async (item: any) => { setSelected(item); setEvents((await getCommandEvents(item.id)).items); };
  return <><Card title="Historial"><CommandTable items={items} onOpen={open} /></Card>{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="modal" onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)}>×</button><h2>{selected.type}</h2><Badge status={selected.status} /><JsonPreview value={{ command: selected, events }} /><div className="actions"><button onClick={() => cancelCommand(selected.id).then(refresh)}>Cancelar</button><button onClick={() => retryCommand(selected.id).then(refresh)}>Reintentar</button></div></div></div>}</>;
}

function Audit() { const [items, setItems] = useState<any[]>([]); useEffect(() => { getAudit().then((r) => setItems(r.items)).catch(() => undefined); }, []); return <Card title="Auditoría"><table><thead><tr><th>Fecha</th><th>Actor</th><th>Acción</th><th>Resultado</th></tr></thead><tbody>{items.map((a) => <tr key={a.id}><td>{shortDate(a.createdAt)}</td><td>{a.actorType}</td><td>{a.action}</td><td>{a.result}</td></tr>)}</tbody></table></Card>; }
function Settings({ user, setUser }: any) { const [setup, setSetup] = useState<any>(null); const [code, setCode] = useState(""); return <section className="grid two"><Card title="Autenticación de dos factores"><p>Estado: <strong>{user.totpEnabled ? "Activado" : "Desactivado"}</strong></p>{!user.totpEnabled && !setup && <button onClick={() => setupTotp().then(setSetup)}>Configurar TOTP</button>}{setup && <><p>Ingresá esta clave en tu autenticador:</p><code className="secret-display">{setup.secret}</code><Field label="Código de 6 dígitos"><input value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))} maxLength={6} /></Field><button className="primary" onClick={() => enableTotp(code).then(() => setUser({ ...user, totpEnabled: true }))}>Activar</button></>}</Card><Card title="Política de seguridad"><ul><li>Cookie HttpOnly y SameSite Strict</li><li>CSRF en mutaciones</li><li>Sesiones revocables</li><li>Agente con token independiente</li><li>Credenciales de publicación sólo locales</li></ul></Card></section>; }

function CommandTable({ items, onOpen }: { items: any[]; onOpen?: (item: any) => void }) { return <div className="table-wrap"><table><thead><tr><th>Creado</th><th>Comando</th><th>Estado</th><th>Etapa</th><th>Progreso</th></tr></thead><tbody>{items.map((c) => <tr key={c.id} onClick={() => onOpen?.(c)} className={onOpen ? "clickable" : ""}><td>{shortDate(c.createdAt)}</td><td>{c.type}</td><td><Badge status={c.status} /></td><td>{c.currentStage}</td><td>{c.progressPercent}%</td></tr>)}</tbody></table></div>; }
function Card({ title, children, className = "" }: any) { return <section className={`card ${className}`}><h2>{title}</h2>{children}</section>; }
function Stat({ label, value, tone = "neutral" }: any) { return <div className={`stat ${tone}`}><span>{label}</span><strong>{value}</strong></div>; }
function Field({ label, children }: any) { return <label className="field"><span>{label}</span>{children}</label>; }
function Badge({ status }: { status: string }) { return <span className={`badge ${status}`}>{status}</span>; }
function StatusDot({ online }: { online: boolean }) { return <span className={`dot ${online ? "online" : "offline"}`} />; }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }
function JsonPreview({ value }: { value: unknown }) { return <pre>{JSON.stringify(value, null, 2)}</pre>; }
function lines(value: string) { return [...new Set(value.split(/\r?\n/).map((x) => x.trim()).filter(Boolean))]; }
function shortDate(value?: string) { return value ? new Date(value).toLocaleString("es-AR") : "—"; }
function message(error: unknown) { return error instanceof Error ? error.message : String(error); }
